### ISSUE TITLE
Bonus #1: Tracking Fishing

### ISSUE THREAD

**Issue by albertchitta** [albertchitta/ASSIGNMENT-Bear-Watcher#8]
- [x] As a user, I should be able to click something on each bear to indicate it has just tried to catch a fish.
- [x] As a user, I should be able to click something on each bear to indicate it has just successfully caught a fish.
- [x] As a user, looking at a bear card I should see time stamps and statuses for each time a bear caught a fish or attempted to catch a fish
- [x] As a user, looking at a bear card, I should see a total number of fish caught tally.

**Comment by albertchitta** [comment]
Completed Bonus #1
